version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudphoto-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ceyy4txtlizd"
s3_prefix = "cloudphoto-backend"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
